// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/bath.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.66, -1.68, -8.19]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-6.98, -0.82, -4.89]}
        //scale={[-0.98, -0.082, -2.89]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={materials.マテリアル}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/bath.glb");
